changelog:
  exclude:
    labels:
      - unverified
      - wont-do
      - rejected
  categories:
    - title: Breaking Changes 🛠
      labels:
        - feature
        - breaking-change
    - title: New Features 🎉
      labels:
        - feature
    - title: Bug Fix 🐞
      labels:
        - "bug"
    - title: Other Changes
      labels:
        - "*"
