name: Bug Report
description: Template for bug reports
title: "[BUG] "
labels: ["bug", "unverified"]
body:
- type: textarea
  attributes:
    label: Expected behaviour
    description: A clear and concise description about the expected behaviour.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual behaviour
    description: A clear and concise description about the actual behaviour.
  validations:
    required: true
- type: textarea
  attributes:
    label: How to reproduce
    description: A clear description of how to reproduce the problem.
    placeholder: |
      1. Go to `...`
      2. Click on `...`
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Logs / Screenshots
    description: If applicable, add logs, screenshots or gifs to help explain your problem.
  validations:
    required: false
- type: input
  attributes:
    label: Lanty version
    description: Clarify the version of Lanty that you are using.
    placeholder: "e.g. v0.1.0 or git SHA"
  validations:
    required: true
- type: input
  attributes:
    label: Operating system and version
    description: The name and version of the operating system you are using.
    placeholder: "e.g. Windows 10, macOS High Sierra or Ubuntu 18.04"
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: If your problem needs further explanation, please add more information here.
  validations:
    required: false